---
# site.yml

- name: Apply Common Configurations to All Nodes
  hosts: all
  become: yes
  roles:
    - common-config

- name: Deploy RKE2 Server Nodes
  hosts: server_nodes
  roles:
    - rke2-server

- name: Install Rancher on designated nodes
  hosts: rancher_nodes
  become: true
  roles:
    - rancher-setup

- name: Deploy RKE2 Worker Nodes
  hosts: worker_nodes
  roles:
    - rke2-worker

