---
# site.yml

- name: Apply Common Configurations to All Nodes
  hosts: all
  become: yes
  roles:
    - common-config

- name: Deploy RKE2 Server Nodes
  hosts: server_nodes
  roles:
    - common-config
    - rke2-server

- name: Deploy RKE2 Worker Nodes
  hosts: worker_nodes
  roles:
    - common-config
    - rke2-worker

