---

- name: Include shared default variables
  ansible.builtin.include_vars:
    file: "../../../shared/defaults.yml"

- name: Install RKE2 worker dependencies
  ansible.builtin.package:
    name: curl
    state: present
  become: true

- name: Download and run the RKE2 installation script for worker nodes
  ansible.builtin.shell:
    cmd: "curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION='{{ rke2_version }}' INSTALL_RKE2_TYPE=agent sh -"
    environment:
      INSTALL_RKE2_CHANNEL: "{{ rke2_channel | default('stable') }}"
  become: true
  when: rke2_version is defined and rke2_channel is defined

- name: Create the RKE2 configuration directory
  ansible.builtin.file:
    path: /etc/rancher/rke2/
    state: directory
    mode: '0755'
  become: true

- name: Fetch RKE2 Server Token from the designated server node
  ansible.builtin.slurp:
    src: /var/lib/rancher/rke2/server/node-token
  register: rke2_server_token
  delegate_to: "{{ groups['server_nodes'][0] }}"
  run_once: true

- name: Configure RKE2 agent to connect to the server
  ansible.builtin.template:
    src: rke2-agent-config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
  become: true
  vars:
    rke2_server_ip: "{{ hostvars[groups['server_nodes'][0]]['ansible_host'] }}"
    rke2_token: "{{ (rke2_server_token.content | b64decode).trim }}"

- name: Enable and start the RKE2 agent service
  ansible.builtin.systemd:
    name: rke2-agent.service
    enabled: yes
    state: started
  become: true

- name: Wait for the RKE2 agent to be ready
  ansible.builtin.wait_for:
    path: /var/lib/rancher/rke2/agent/kubelet.kubeconfig
    state: present
    timeout: 300
  become: true
